name: OnePiece-Mod
version: "${project.version}"
author: Lastril
main: fr.lastril.onepiecemod.OnePieceMod
website: "${project.url}"
description: "${project.description}"
depend: [ SmartInvs ]
softdepend: [ Apollo-Bukkit ]
commands:
  vanish:
    description: Permet de se mettre invisible aux yeux de tout les joueurs sur le serveur
  topluck:
    description: Permet de voir le nombre d'or et de diamants minés par joueur sur le serveur
  alert:
    description: Permet d'activer/désactiver les alertes